### ISSUE TITLE
Making <details> tags nicer

### ISSUE THREAD

**Issue by mariegold** [bettermathematics/bettermathematics.github.io#46]
On the Start page, a lot of content is hidden using the `<details>` tag. It breaks a line and thus occupies a lot of space. Using the `<summary>` feature does not work on Firefox (it makes the arrows disappear and therefore it is not clear that one should click on it). 

It would be nice if someone found a better, more aesthetic solution.

**Comment by eonu** [comment]
Implemented in #51.
